# Generated by Django 5.2.6 on 2025-09-26 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSecreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Elogio/Mensagem')),
                ('destinatario', models.CharField(choices=[('E', 'Ela'), ('N', 'Nós'), ('M', 'Motivacional')], default='E', max_length=1, verbose_name='Para Quem?')),
                ('data_agendada', models.DateField(blank=True, null=True, verbose_name='Agendar para o dia')),
                ('ultima_vez_exibida', models.DateTimeField(blank=True, null=True, verbose_name='Última exibição')),
            ],
            options={
                'verbose_name': 'Mensagem Secreta',
                'verbose_name_plural': 'Mensagens Secretas',
            },
        ),
    ]
