# Generated by Django 5.2.6 on 2025-09-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemSecreta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Elogio/Mensagem')),
                ('destinatario', models.CharField(choices=[('E', 'Ela'), ('N', 'Nós'), ('M', 'Motivacional')], default='E', max_length=1, verbose_name='Para Quem?')),
                ('tema_cor', models.CharField(choices=[('rosa', 'Rosa Suave'), ('azul', 'Azul Sereno'), ('verde', 'Verde Calmo'), ('amarelo', 'Amarelo Quente')], default='rosa', max_length=10, verbose_name='Tema de Cor')),
                ('contagem_coracoes', models.PositiveIntegerField(default=0, verbose_name='Contagem de Corações')),
                ('data_agendada', models.DateField(blank=True, null=True, verbose_name='Agendar para o dia')),
                ('ultima_vez_exibida', models.DateTimeField(blank=True, null=True, verbose_name='Última exibição')),
            ],
            options={
                'verbose_name': 'Mensagem Secreta',
                'verbose_name_plural': 'Mensagens Secretas',
            },
        ),
    ]
