# Generated by Django 5.2.6 on 2025-09-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsecreta',
            name='tema_cor',
            field=models.CharField(choices=[('rosa', 'Rosa Suave'), ('azul', 'Azul Sereno'), ('verde', 'Verde Calmo'), ('amarelo', 'Amarelo Quente')], default='rosa', max_length=10, verbose_name='Tema de Cor'),
        ),
    ]
