# Generated by Django 5.2.6 on 2025-09-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagens', '0002_mensagemsecreta_tema_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagemsecreta',
            name='contagem_coracoes',
            field=models.PositiveIntegerField(default=0, verbose_name='Contagem de Corações'),
        ),
    ]
